p8105_hw2_mgw2144
================
2023-09-27

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(here)
```

    ## here() starts at C:/Users/magno/Desktop/p8105_hw2_mgw2144

``` r
rm(list=ls())
project.folder=
  paste0(print(here::here()),'/')
```

    ## [1] "C:/Users/magno/Desktop/p8105_hw2_mgw2144"

Problem 1

``` r
month_df = 
  tibble(
    month_num = 1:12,
    month_abb = month.abb,
    month = month.name
  )

pols_df =
  read_csv(paste0(project.folder,"/data/pols-month.csv")) |>
  separate(mon, into = c("year", "month_num", "day"), convert = TRUE) |>
  mutate(
    president = recode(prez_gop, "0" = "dem", "1" = "gop", "2" = "gop")) |>
  left_join(x = _, y = month_df) |> 
  select(year, month, everything(), -day, -prez_gop, -prez_dem)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
    ## Joining with `by = join_by(month_num)`

``` r
snp_df = 
 read_csv(paste0(project.folder,"/data/snp.csv"),
  col_types = cols(date = col_date(format = "%m/%d/%y"))) |>
  separate(date, into = c("year", "month_num", "day"), convert = TRUE) |>
  mutate(
    year = if_else(year > 2023, year - 100, year)) |> 
  left_join(x = _, y = month_df) |> 
  select(year, month, close) 
```

    ## Joining with `by = join_by(month_num)`

``` r
unemployment_df = 
 read_csv(paste0(project.folder,"/data/unemployment.csv")) %>% 
  rename(year = Year) %>% 
  pivot_longer(
    Jan:Dec,
    names_to = "month_abb",
    values_to = "unemployment"
  ) |> 
  left_join(x = _, y = month_df) |> 
  select(year, month, unemployment)
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
    ## Joining with `by = join_by(month_abb)`

merge step

``` r
data_538 = 
  left_join(pols_df, snp_df) |>
  left_join(x = _, y = unemployment_df)
```

    ## Joining with `by = join_by(year, month)`
    ## Joining with `by = join_by(year, month)`

``` r
str(data_538)
```

    ## tibble [822 × 13] (S3: tbl_df/tbl/data.frame)
    ##  $ year        : num [1:822] 1947 1947 1947 1947 1947 ...
    ##  $ month       : chr [1:822] "January" "February" "March" "April" ...
    ##  $ month_num   : int [1:822] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ gov_gop     : num [1:822] 23 23 23 23 23 23 23 23 23 23 ...
    ##  $ sen_gop     : num [1:822] 51 51 51 51 51 51 51 51 51 51 ...
    ##  $ rep_gop     : num [1:822] 253 253 253 253 253 253 253 253 253 253 ...
    ##  $ gov_dem     : num [1:822] 23 23 23 23 23 23 23 23 23 23 ...
    ##  $ sen_dem     : num [1:822] 45 45 45 45 45 45 45 45 45 45 ...
    ##  $ rep_dem     : num [1:822] 198 198 198 198 198 198 198 198 198 198 ...
    ##  $ president   : chr [1:822] "dem" "dem" "dem" "dem" ...
    ##  $ month_abb   : chr [1:822] "Jan" "Feb" "Mar" "Apr" ...
    ##  $ close       : num [1:822] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ unemployment: num [1:822] NA NA NA NA NA NA NA NA NA NA ...

The `pols_df` data has 822 observations and 11 variables and tells us
about the party affiliation distribution (democrat or republican) for
governors and senators for a given year from years 1947 to 2015. The
dataset also tells us if the sitting president was a democrat or
republican. The `snp_df` data has 787 observations and 3 variables,
ranging from years 1950 to 2015. The `unemployment_df` data has 816
observations and 3 variables ranging from years 1948 to 2015. In
Januarys in or after 1975 in which a democrat was president, the average
unemployment rate was 6.57. The average unemployment rate over the same
time period in which a republican was president was 6.47.

Problem 2

``` r
mr_trash_wheel=
  readxl::read_excel(paste0(project.folder,"/data/202309 Trash Wheel Collection Data.xlsx"), sheet = 1, range = "A2:N586") %>%
  janitor::clean_names() %>% 
  mutate(
    homes_powered=((weight_tons*500)/30),
    year = as.integer(year),
    trash_data = "mr_tw")%>% 
  relocate(trash_data)
```

``` r
professor_trash_wheel=
  readxl::read_excel(paste0(project.folder,"/data/202309 Trash Wheel Collection Data.xlsx"), sheet=2, range = "A2:M108") %>% 
  janitor::clean_names() %>% 
  mutate(homes_powered=(
    (weight_tons*500)/30),
    year = as.integer(year),
    trash_data = "professor_tw")%>% 
  relocate(trash_data)
```

``` r
gwynnda_trash_wheel=
  readxl::read_excel(paste0(project.folder,"/data/202309 Trash Wheel Collection Data.xlsx"), sheet=4, range = "A2:L157") %>% 
  janitor::clean_names() %>% 
  mutate(homes_powered=(
    (weight_tons*500)/30), 
    year = as.integer(year), 
    trash_data = "gwynnda_tw")%>% 
  relocate(trash_data)

gwynnda_july_2021=
  gwynnda_trash_wheel %>% 
  filter(month == "July") %>% 
  filter(year == "2021")
```

``` r
trash_wheel_total=
  bind_rows(mr_trash_wheel, professor_trash_wheel, gwynnda_trash_wheel) %>%
  janitor::clean_names()
```

The collection of Mr. Trash Wheel datasets records information of a
water-wheel vessel tht removed trash from the Inner Harbor in Baltimore,
Maryland. The combined dataset created above contains information from
the Mr. Trash Wheel, Professor Trash Wheel, and Gywnnda Trash Wheel
datasets with a total of 845 observations. The total weight of trash
collected by Professor Trash Wheel was 216.26 tons. The total number of
cigarette butts collected by Gwynnda in July of 2021 is 1.63^{4}.

Problem 3

``` r
mci_baseline=
  read_csv(paste0(project.folder,"/data/MCI_baseline.csv"), skip = 1) %>% 
  janitor::clean_names() 
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
mci_baseline_clean=
  mci_baseline %>% 
  mutate(sex = recode(sex, `1` = "male", `0`="female")) %>% 
  mutate(apoe4 = recode(apoe4, `1`="carrier", `0`="non-carrier")) %>% 
  filter(age_at_onset > current_age | age_at_onset == ".") 

mci_apoe_c=
  mci_baseline_clean %>% 
  filter(sex == "female") %>% 
  filter(apoe4 == "carrier") %>% 
  mutate(apoe4 = recode(apoe4, "carrier" = 1))
  
mci_apoe_nc=
  mci_baseline_clean %>% 
  filter(sex == "female") %>% 
  filter(apoe4 == "non-carrier") %>% 
   mutate(apoe4 = recode(apoe4, "non-carrier" = 1))
```

Important steps in the import process include utilizing the read_csv()
function to import the data so that it can be cleaned and manipulated.
Important features of the dataset include patient ID number, sex, APOE4
gene carrier status, and age of MCI onset for participants. There were
originally 483 participants recruited and 479 of these participants were
MCI free at baseline. The average baseline age is 65.0286013 years old.
30 percent of women in the study are APOE4 carriers.

``` r
mci_amyloid=
  read_csv(paste0(project.folder,"/data/mci_amyloid.csv"), skip = 1) %>% 
  janitor::clean_names() %>% 
  rename("time_0" = baseline) %>%  
  rename("id" = study_id) %>% 
  pivot_longer(
    time_0:time_8,
    names_to = "time",
    values_to = "amyloid_value"
  ) 
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

The import process for this data set involves reading in the csv file
for the mci_amyloid data utilizing its relative path name. Some of the
prominent features of the dataset include patient ID number, and the
time elapsed since the study baseline to the visit where the biomarker
Amyloid \_ 42/40 ratio was measured marked at baseline and years 2, 4,
6, and 8, and the amyloid value recorded at these times. In cleaning the
dataset I changed the column name of participant IDs from “study_id” to
“id” to match the “id” column name in the baseline data and changed the
“baseline” variable to “time_0”. The new dataset has 487 rows and 3
columns. I used the pivot_long function to change the time column names
into variables in a new “time” column with their corresponding amyloid
values for each unique patient ID number.

``` r
mci_unique=
  anti_join(mci_baseline_clean, mci_amyloid, by = "id")
```

There are 8 patients that are only in the baseline or amyloid datasets,
patient ids: 14, 49, 92, 179, 268, 304, 389, and 412. These patients
were found using the anti_join() function connecting the
mci_baseline_clean and mci_amyloid datasets.

``` r
mci_combine=
  inner_join(mci_baseline_clean, mci_amyloid, by = "id")
```

The dataset “mci_combine” was created by merging only the data on
participants in both the “mci_baseline” and “mci_amyloid” datasets
throug the inner_join() function. The combined dataset has 2355 rows and
8 columns with a total of 471 participants. The prominent variables in
this dataset are patient id (“id”), age at baseline “current_age”, sex,
education level (“education”), whether or not they are an APoE4 gene
carrier, age at onset of MCI, time in years from baseline when amyliod
values were tested “time”, and amyloid value at those time intervals.

``` r
write_csv(mci_combine, "mci_combined_data.csv")
```
