---
title: "p8105_hw2_mgw2144"
output: github_document
date: "2023-09-27"
---

```{r}
library(here)
library(tidyverse)
rm(list=ls())
project.folder=
  paste0(print(here::here()),'/')
```

Problem 1

```{r}
pols_month_df =
  read.csv(paste0(project.folder,"data/pols-month.csv")) %>% 
  janitor::clean_names()%>% 
  separate(mon, into = c("year", "month", "day")) %>% 
  mutate(
    month = replace(month, month == "01", "january"),
    month = replace(month, month == "02", "february"),
    month = replace(month, month == "03", "march"),
    month = replace(month, month == "04", "april"),
    month = replace(month, month == "05", "may"),
    month = replace(month, month == "06", "june"),
    month = replace(month, month == "07", "july"),
    month = replace(month, month == "08", "august"),
    month = replace(month, month == "09", "september"),
    month = replace(month, month == "10", "october"),
    month = replace(month, month == "11", "november"),
    month = replace(month, month == "12", "december")
  ) %>% 
  select(-day)
```
#########
create a president variable taking values gop and dem, and remove prez_dem and prez_gop; and remove the day variable.
#########

```{r}
snp_df = 
 read.csv(paste0(project.folder,"data/snp.csv")) %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("month", "day", "year")) %>% 
  mutate(
    month = replace(month, month == "1", "january"),
    month = replace(month, month == "2", "february"),
    month = replace(month, month == "3", "march"),
    month = replace(month, month == "4", "april"),
    month = replace(month, month == "5", "may"),
    month = replace(month, month == "6", "june"),
    month = replace(month, month == "7", "july"),
    month = replace(month, month == "8", "august"),
    month = replace(month, month == "9", "september"),
    month = replace(month, month == "10", "october"),
    month = replace(month, month == "11", "november"),
    month = replace(month, month == "12", "december")
  ) %>% 
  select(-day) %>% 
  relocate(year, month)
```

